### ISSUE TITLE
ERR_BUFFER_OUT_OF_BOUNDS

### ISSUE THREAD

**Issue by mmiszy** [joe-bell/plaiceholder#157]
**Describe the bug**

```
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:81:11)
    at Buffer.readUInt16LE (internal/buffer.js:240:5)
    at Object.validate (/project/node_modules/plaiceholder/dist/index.js:3557:18)
    at finder (/project/node_modules/plaiceholder/dist/index.js:4538:51)
    at Array.find (<anonymous>)
    at Object.detector (/project/node_modules/plaiceholder/dist/index.js:4540:17)
    at lookup (/project/node_modules/plaiceholder/dist/index.js:4606:29)
    at imageSize (/project/node_modules/plaiceholder/dist/index.js:4692:14)
    at getImageSize (/project/node_modules/plaiceholder/dist/index.js:4741:7)
    at loadImage (/project/node_modules/plaiceholder/dist/index.js:4781:23) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
```

When trying to get plaiceholder of the following image: `https://res.cloudinary.com/type-of-web/image/fetch/https%3A%2F%2Fog.typeofweb.com%2Fapi%3FoverlayColor%3D4e2d53%26overlayOpacity%3D0.6%26text%3D**Kt%25C3%25B3ry%2Bhosting%2Bjest%2Bnajszybszy%253F**%250A%25F0%259F%258F%258E%25F0%259F%2592%25A8%2B%2B9%2Brzeczy%252C%2Bkt%25C3%25B3re%2Bmaj%25C4%2585%250Anajwi%25C4%2599ksze%2Bznaczenie%26fontSize%3D110%26gap%3D110&`

**Comment by joe-bell** [comment]
Sorry, there's not enough info here to work with. I'll need a full reproduction and Node version to investigate further (have a feeling you might be on an older Node version or the file type is incompatible)

…but to be super honest here, I'm not a Node.js expert and haven't encountered this error before. Can't promise I'll be much help here I'm afraid!
